# Generated by Django 5.2.4 on 2025-07-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_alter_cartitem_cart_alter_cartitem_is_active_and_more'),
        ('shop', '0002_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='variation',
            field=models.ManyToManyField(blank=True, to='shop.variation'),
        ),
    ]
