# Generated by Django 5.2.4 on 2025-08-04 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'product gallery', 'verbose_name_plural': 'product gallery'},
        ),
    ]
