# Generated by Django 5.2.4 on 2025-07-19 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_zip_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='zip_code',
            new_name='pin_code',
        ),
    ]
